import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import type { Exercise, Session, UserAnswer } from "@/context/SessionContext";
import { visualToSvg } from "./visualToSvg";

export type PdfMode = "blank" | "completed";

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatUserAnswer(ans: UserAnswer | undefined): string {
  if (ans === undefined || ans === null) return "—";
  if (typeof ans === "string") return ans;
  if ("marked" in ans) return ans.marked.length ? ans.marked.join(", ") : "—";
  if ("connections" in ans) return ans.connections.map((c) => `${c.left} ↔ ${c.right}`).join(" · ") || "—";
  if ("strokes" in ans) return `(drawing — ${ans.strokes.length} strokes)`;
  return "—";
}

function renderExerciseBlock(ex: Exercise, idx: number, mode: PdfMode): string {
  const numLabel = String(idx + 1).padStart(2, "0");
  const optionsHtml =
    ex.options && ex.options.length
      ? `<ol class="options">${ex.options
          .map((opt) => {
            const isCorrect = mode === "completed" && ex.answer && opt.trim().toLowerCase() === ex.answer.trim().toLowerCase();
            return `<li class="${isCorrect ? "correct" : ""}">${escapeHtml(opt)}</li>`;
          })
          .join("")}</ol>`
      : "";

  const visualHtml = ex.visual ? `<div class="visual">${visualToSvg(ex.visual)}</div>` : "";

  const answerSlot =
    mode === "completed"
      ? `<div class="answerSlot completed"><span class="label">Answer</span><span class="text">${escapeHtml(formatUserAnswer(ex.userAnswer))}</span></div>
         ${ex.answer ? `<div class="answerSlot expected"><span class="label">Correct</span><span class="text">${escapeHtml(ex.answer)}</span></div>` : ""}`
      : `<div class="answerSlot blank"><span class="label">Answer</span><span class="line"></span></div>`;

  return `
    <li class="exercise">
      <div class="head">
        <span class="num">${numLabel}</span>
        <p class="question">${escapeHtml(ex.question)}</p>
      </div>
      ${visualHtml}
      ${optionsHtml}
      ${answerSlot}
    </li>
  `;
}

function buildHtml(session: Session, mode: PdfMode): string {
  const title = session.title ?? session.topic ?? "Worksheet";
  const date = new Date(session.createdAt).toLocaleDateString();
  const summary = mode === "completed"
    ? `<p class="summary">${session.totalCorrect ?? 0} of ${session.exercises.length} correct</p>`
    : "";
  const exercises = session.exercises.map((ex, i) => renderExerciseBlock(ex, i, mode)).join("");

  return `<!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(title)}</title>
    <style>
      @page { size: A4; margin: 18mm 14mm; }
      * { box-sizing: border-box; }
      body { font-family: -apple-system, "Helvetica Neue", Helvetica, Arial, sans-serif; color: #3A3A3A; background: #FFFFFF; }
      .header { display: flex; align-items: baseline; justify-content: space-between; border-bottom: 2px solid #A76A4A; padding-bottom: 8px; margin-bottom: 16px; }
      .header h1 { font-size: 22px; margin: 0; color: #8A5538; }
      .header .meta { font-size: 11px; color: #8A8378; }
      .summary { font-size: 12px; color: #5C9659; margin: 0 0 16px 0; }
      ol.exercises { list-style: none; padding: 0; margin: 0; }
      li.exercise { padding: 12px 0 16px 0; border-bottom: 1px solid #E5DDC9; page-break-inside: avoid; }
      .head { display: flex; gap: 10px; align-items: flex-start; }
      .head .num { font-weight: 700; color: #8A8378; font-size: 11px; letter-spacing: 1px; padding-top: 2px; }
      .head .question { margin: 0; font-size: 14px; line-height: 1.45; }
      .visual { margin: 10px 0 6px 28px; }
      .options { list-style: upper-alpha; padding-left: 50px; margin: 8px 0; }
      .options li { font-size: 13px; padding: 2px 0; }
      .options li.correct { font-weight: 700; color: #5C9659; }
      .answerSlot { margin: 8px 0 0 28px; display: flex; align-items: center; gap: 8px; }
      .answerSlot .label { font-size: 10px; letter-spacing: 1px; color: #8A8378; font-weight: 700; text-transform: uppercase; }
      .answerSlot .line { display: inline-block; flex: 1; height: 1px; border-bottom: 1.5px solid #3A3A3A; min-width: 120px; }
      .answerSlot .text { font-size: 13px; font-weight: 600; color: #8A5538; }
      .answerSlot.expected .text { color: #5C9659; }
      .footer { margin-top: 20px; font-size: 10px; color: #8A8378; text-align: center; }
    </style>
  </head>
  <body>
    <div class="header">
      <h1>${escapeHtml(title)}</h1>
      <span class="meta">${date}${session.grade ? ` · Grade ${escapeHtml(session.grade)}` : ""}</span>
    </div>
    ${summary}
    <ol class="exercises">${exercises}</ol>
    <div class="footer">Generated by MarmotMakesMath</div>
  </body>
  </html>`;
}

export async function exportSessionAsPdf(session: Session, mode: PdfMode): Promise<string | null> {
  const html = buildHtml(session, mode);
  const { uri } = await Print.printToFileAsync({ html });
  if (!uri) return null;
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: mode === "completed" ? "Completed worksheet" : "Blank worksheet",
      UTI: "com.adobe.pdf",
    });
  }
  return uri;
}

export async function printSession(session: Session, mode: PdfMode): Promise<void> {
  const html = buildHtml(session, mode);
  await Print.printAsync({ html });
}
